name: Wireframe

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: python -m pip install build

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1